version: '2'
services:
  nginx:
    build: nginx
    command: nginx -g "daemon off;"
    links:
      - tomcat
    container_name: app_nginx
    ports:
      - "80:80"
  tomcat:
    build: tomcat
    container_name: app_tomcat
    ports:
      - "8080:8080"
